### ISSUE TITLE
I really like the design, but it just doesn't work/run.

### ISSUE THREAD

**Issue by clivebearmanhub** [rosoftdeveloper/appseed#1]
Hey there,

Sorry to sound like a whiner, but I couldn't get this project to work at all. It might be my inexperience, but here's what I've found so far.
1. There's no clone or download button on the repo, so had to use another tool so used DownGit to copy the structure (https://minhaskamal.github.io/DownGit)
2. I'm using python 3 and I think the code is mainly python 2
3. There's not enough basic instruction to setup.  "Clone repo, setup db and run python" are the steps, but there's really no explanation about how to set up the database.
4. After running app.py - get <ModuleNotFoundError: No module named 'assets'>

I really like this look and am willing to help fix issues.

Thanks

**Comment by rosoftdeveloper** [comment]
Hello, 
what project? Now-Ui-Dashboard or Light?

My advice is to clone the project from Github and follow the steps listed in README files. 

I'm here, if you need help.

Cheers!
Adi - [AppSeed](www.AppSeed.us)

**Comment by clivebearmanhub** [comment]
Thanks.  I cloned the whole repo and tried BOTH flask apps.  Both gave me <ModuleNotFoundError: No module named 'assets'> when running ">python app.py"

**Comment by RyanSchattner** [comment]
I had the same issues. Also using python 3. It looks like module import doesn't work for some reason. I commented out assets, then it couldn't find models module. I gonna try copy pasting this all through to a new project and see if that maybe helps.

**Comment by rosoftdeveloper** [comment]
Hello guys, 
I will update the repo to be usable in python3. 
Also, some directories will be renamed.  

See u

**Comment by RyanSchattner** [comment]
For a quick fix I am just going through updating for directories when importing ie. `from app.assets import Assets as assets` to make it work if anyone else has this issue.

**Comment by RyanSchattner** [comment]
got it all almost working now. Last issue I am encountering is `"Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)"` Any ideas on a fix?

**Comment by rosoftdeveloper** [comment]
Hello Guys, 

We have finished the new structure for this project. Now we provide staters for backend & react, Vue.js UI-Kits. 

And .. we will provide constant support. :) because a dedicated resource will monitor this repo.

Cheers!
